#+title:  Free nets

This repository contains code accompanying the paper "Any-dimensional equivariant neural networks". It includes simple implementations of the computational recipe defined in the paper and scripts to run all the numerical experiments in the paper.

*Warning: the instructions assume that your current working directory is the base of this repository.*

* One-time setup
For the following instructions, you will need Python 3.9 and pip installed. Consider creating a virtual environment for this project. For example, by running:
#+begin_src shell
$ python -m venv .venv
$ source .venv/bin/activate
#+end_src

Then, install the requirements:
#+begin_src shell
$ pip install -e .[EXPTS]
#+end_src

* Running experiments
All the scripts to run the numerical examples are in the =experiments= folders. Here is a table with all the scripts.
| *Script*                       |
| =free_trace.py=                |
| =free_diagonal_extraction.py=  |
| =free_symmetric_projection.py= |
| =free_singular_vector.py=      |
| =free_O_invariant.py=          |

 The results will be saved to a new folder within the =results= directory.

 *Warning: running any of this experiments might take a while.*

* Generating figures

After running any of the scripts above, you will have a new folder within the directory =results/<name_of_experiment>=. Modify the last few lines of the script =experiments/generate_figures.py= to include said folder. Run
#+begin_src shell
$ python generate_figures.py
#+end_src
this will generate images like the ones in the paper. If you don't modify the path in this script, it will simply generate the figures in the paper.
